<h1 style="text-align: center">Implementation of a single layer neural network</h1>

Lakhder Amine - 2022-2023 - Master SDSI - Deep Learning

## Dependencies

In [2]:
import pandas as pd
import numpy as np
import math

from ann.singleLayerNeuralNetwork import SingleLayerNeuralNetwork

## AND Operator

In [3]:
data = pd.read_csv('./data/data.csv')

In [4]:
def split_data(data):
    
    y = data['r']
    X = data.drop(labels='r',axis=1)
    
    y_train = y.iloc[:math.floor(data.shape[0]*0.7)]
    X_train = X.iloc[:math.floor(data.shape[0]*0.7)]
    
    X_test = X.iloc[math.floor(data.shape[0]*0.7):]
    y_test = y.iloc[math.floor(data.shape[0]*0.7):]
    
    return X_train,y_train,X_test,y_test


In [5]:
X_train,y_train,X_test,y_test = split_data(data)

def activation_function(s): 
    if s > 1.8:
        return 1
    return 0

In [60]:
model = SingleLayerNeuralNetwork(iterations=100,activation_function=activation_function,weights_interval=[0,1],biais=1,alpha=0.1)

In [61]:
model.fit(X=X_train,y=y_train)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
model.weights

x1    0.3
x2    0.4
x3    0.4
x4    0.4
Name: 1, dtype: float64

In [63]:
model.predict(X_test)

array([0., 0., 0., 0., 1.])

## Even or Odd

In [10]:
even_odd_data = pd.read_csv('./data/even_odd_data.csv')

In [29]:
X_train_1,y_train_1,X_test_1,y_test_1 = split_data(even_odd_data)

def even_odd_activation_function(s):
    if s >= 1:
        return 1
    return 0

In [30]:
model_even_odd = SingleLayerNeuralNetwork(iterations=100,activation_function=even_odd_activation_function,weights_interval=[0,1],biais=1,alpha=0.1)

In [31]:
model_even_odd.fit(X_train_1,y_train_1)

array([0., 1., 0., 1., 0., 1., 0.])

In [32]:
model_even_odd.weights

x1    0.3
x2    0.2
x3    0.1
x4    0.0
x5   -0.5
x6   -0.1
x7   -0.1
Name: 0, dtype: float64

In [33]:
model_even_odd.predict(X_test_1)

array([1., 0., 1.])