<h1 style="text-align: center">Implementation of a single layer neural network</h1>

Lakhder Amine - 2022-2023 - Master SDSI - Deep Learning

## Dependencies

In [1]:
import pandas as pd
import numpy as np
import math

from ann.singleLayerNeuralNetwork import SingleLayerNeuralNetwork

## AND Operator

In [2]:
data = pd.read_csv('./data/data.csv')

In [3]:
def split_data(data):
    
    y = data['r']
    X = data.drop(labels='r',axis=1)
    
    y_train = y.iloc[:math.floor(data.shape[0]*0.7)]
    X_train = X.iloc[:math.floor(data.shape[0]*0.7)]
    
    X_test = X.iloc[math.floor(data.shape[0]*0.7):]
    y_test = y.iloc[math.floor(data.shape[0]*0.7):]
    
    return X_train,y_train,X_test,y_test


In [4]:
X_train,y_train,X_test,y_test = split_data(data)

def activation_function(s): 
    if s > 1.8:
        return 1
    return 0

In [5]:
model = SingleLayerNeuralNetwork(iterations=100,activation_function=activation_function,weights_interval=[0,1],biais=1,alpha=0.1)

In [6]:
model.fit(X=X_train,y=y_train)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
model.weights

x1    0.4
x2    0.4
x3    0.4
x4    0.3
Name: 3, dtype: float64

In [8]:
model.predict(X_test)

array([0., 0., 0., 0., 1.])

## Or Operator

In [9]:
or_data = pd.read_csv('./data/or_data.csv')

In [25]:
X_train_0,y_train_0,X_test_0,y_test_0 = split_data(or_data)

def or_activation_function(s):
    if s >= 1.8:
        return 1
    return 0

In [30]:
model_or = SingleLayerNeuralNetwork(iterations=100,activation_function=or_activation_function,weights_interval=[0,1],biais=1,alpha=0.1)

In [31]:
model_or.fit(X_train_0,y_train_0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
model_or.weights

x1    0.6
x2    0.9
x3    0.9
x4    0.4
Name: 0, dtype: float64

In [33]:
model_or.predict(X_test_0)

array([1., 1., 1., 1., 0.])

## Even or Odd

In [10]:
even_odd_data = pd.read_csv('./data/even_odd_data.csv')

In [11]:
X_train_1,y_train_1,X_test_1,y_test_1 = split_data(even_odd_data)

def even_odd_activation_function(s):
    if s >= 1:
        return 1
    return 0

In [12]:
model_even_odd = SingleLayerNeuralNetwork(iterations=100,activation_function=even_odd_activation_function,weights_interval=[0,1],biais=1,alpha=0.1)

In [13]:
model_even_odd.fit(X_train_1,y_train_1)

array([0., 1., 0., 1., 0., 1., 0.])

In [14]:
model_even_odd.weights

x1    0.3
x2    0.1
x3    0.3
x4    0.1
x5   -0.5
x6   -0.1
x7   -0.1
Name: 0, dtype: float64

In [15]:
model_even_odd.predict(X_test_1)

array([1., 0., 1.])